name: C++ CI/CD Pipeline - cem.tomas3

on: 
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ doxygen graphviz docker.io

    - name: Compile main application
      run: g++ -o fraction_app fraction.cpp main.cpp

    - name: Compile tests
      run: g++ -o test_app fraction.cpp test.cpp

    - name: Run tests
      run: ./test_app

    - name: Generate documentation
      run: doxygen Doxyfile

    - name: Build Docker image
      run: docker build -t fraction-app .

    - name: Run Docker container
      run: docker run --rm fraction-app

    - name: Upload documentation
      uses: actions/upload-artifact@v4
      with:
        name: documentation
        path: docs/
