name: C++ CI/CD Pipeline - cem.tomas3

on: [push, pull_request]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y g++ doxygen graphviz

    - name: Compile main application
      run: g++ -o fraction_app fraction.cpp main.cpp

    - name: Compile tests
      run: g++ -o test_app fraction.cpp test.cpp

    - name: Run tests
      run: ./test_app

    - name: Generate documentation
      run: doxygen Doxyfile

    - name: Build Docker image
      run: docker build -t fraction-app-cem-tomas3 .

    - name: Run Docker container
      run: docker run --rm fraction-app-cem-tomas3
