name: C++ CI/CD Pipeline - cem.tomas3

on: 
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y g++ doxygen graphviz
      
    - name: Compile program
      run: g++ -o fraction_app fraction.cpp main.cpp
      
    - name: Compile tests
      run: g++ -o test_app fraction.cpp test.cpp
      
    - name: Run tests
      run: ./test_app
      
    - name: Generate docs
      run: doxygen Doxyfile
      
    - name: Success message
      run: echo "✅ All tests passed! CI/CD is working!"
