name: C++ CI/CD Pipeline
on: workflow_dispatch

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11  # ✅ الإصدار الصحيح
        
      - name: Install tools
        run: sudo apt-get update && sudo apt-get install -y g++ doxygen graphviz
        
      - name: Compile and test
        run: |
          g++ -o fraction_app fraction.cpp main.cpp
          g++ -o test_app fraction.cpp test.cpp
          ./test_app
          doxygen Doxyfile
          echo "✅ All tests passed! Project: cem.tomas3"
